const parts=[
['철통 투구','기사','방어 +3',{armor:3}],['별빛 모자','마법','주문 피해 +5',{magic:5}],['선풍기 머리','기계','공격 속도 +15%',{speed:.15}],['고양이 머리','야생','회피 +12%',{evade:.12}],
['기사 갑옷','기사','체력 +40 · 방어 +3',{hp:40,armor:3,speed:-.1}],['마법사 로브','마법','주문 피해 +6',{magic:6}],['골판지 몸통','기계','체력 +25',{hp:25}],['선인장 몸통','야생','피격 시 가시 피해 4',{thorns:4,hp:15}],
['강철 장화','기사','방어 +2 · 체력 +15',{armor:2,hp:15}],['용수철 다리','기계','공격 속도 +12%',{speed:.12}],['롤러스케이트','야생','공격 속도 +25%',{speed:.25}],['유령 꼬리','마법','회피 +15%',{evade:.15}],
['종이 방패','기사','방어 +3',{armor:3}],['지우개','마법','공격마다 상대 방어 감소',{erase:1}],['손풍기','기계','공격 속도 +20%',{speed:.2}],['말굽 자석','기계','상대 공격 속도 -15%',{slow:.15}],
['낙서검','기사','공격력 +10',{atk:10}],['불꽃검','마법','공격력 +6 · 누적 화상',{atk:6,burn:2}],['연필 창','야생','공격력 +8 · 관통 3',{atk:8,pierce:3}],['왕망치','기계','공격력 +20 · 속도 -25%',{atk:20,speed:-.25,pierce:5}]
].map((p,id)=>({id,name:p[0],family:p[1],desc:p[2],stats:p[3],slot:Math.floor(id/4)}));
const recipes=[{name:'불어라, 불꽃!',ids:[2,17],desc:'선풍기 머리 + 불꽃검 · 화상 중첩량 +3',bonus:{burn:3}},{name:'고쳐 그린 약점',ids:[13,18],desc:'지우개 + 연필 창 · 관통 +6',bonus:{pierce:6}},{name:'쿵! 내려찍기',ids:[9,19],desc:'용수철 다리 + 왕망치 · 매 3번째 공격 기절',bonus:{stun:1}},{name:'움직이는 고슴도치',ids:[7,10],desc:'선인장 몸통 + 롤러스케이트 · 가시 피해 +6',bonus:{thorns:6}},{name:'골판지 태풍',ids:[6,14],desc:'골판지 몸통 + 손풍기 · 속도 +35%',bonus:{speed:.35}},{name:'유령 고양이',ids:[3,11],desc:'고양이 머리 + 유령 꼬리 · 회피 +15%',bonus:{evade:.15}}];
const names=['머리','상체','하체','왼손 무기','오른손 무기'], positions=['head','body','legs','left','right'];
const starters=parts.filter(p=>![3,7,11,15,19].includes(p.id)).map(p=>p.id);
let saved={};try{saved=JSON.parse(localStorage.getItem('doodle-v1')||'{}')}catch{}
let unlocked=new Set([...starters,...(Array.isArray(saved.unlocked)?saved.unlocked.filter(n=>Number.isInteger(n)&&n>=0&&n<20):[])]),wins=Number.isInteger(saved.wins)&&saved.wins>=0?saved.wins:0;
let selected=[null,null,null,null,null],rolls=[0,0,0,0,0],busy=new Set(),mode='build',round=1,opponent,combat,clockId,elapsed=0;
const $=id=>document.getElementById(id);const rand=a=>a[Math.floor(Math.random()*a.length)];
function sprite(id){return `background-position:${(id%4)*100/3}% ${Math.floor(id/4)*25}%`}
function matches(ids){return recipes.filter(r=>r.ids.every(i=>ids.includes(i)))}
function stats(ids){let s={hp:110,atk:8,armor:0,speed:1,magic:0,evade:0,pierce:0,burn:0,thorns:0,erase:0,slow:0,stun:0,shield:0,echo:0};const add=o=>{for(const [k,v]of Object.entries(o))s[k]=(s[k]||0)+v};ids.filter(i=>i!==null).forEach(i=>add(parts[i].stats));matches(ids).forEach(r=>add(r.bonus));let families={};ids.filter(i=>i!==null).forEach(i=>{let f=parts[i].family;families[f]=(families[f]||0)+1});if(families['기사']>=2)s.shield=18;if(families['마법']>=2)s.echo=1;if(families['기계']>=2)s.speed+=.15;if(families['야생']>=2)s.evade+=.08;s.evade=Math.min(.5,s.evade);s.speed=Math.max(.4,s.speed);return {...s,families}}
function puppet(el,ids){el.innerHTML=ids.map((id,i)=>id===null?`<div class="piece ${positions[i]} empty-piece">?</div>`:`<div class="piece ${positions[i]}" style="${sprite(id)}"></div>`).join('')}
function chooseEnemy(){const opponents=[{name:'철벽의 낙서 기사',ids:[0,4,8,12,16],hint:'두꺼운 갑옷! 연필 창의 관통이나 불꽃검의 화상으로 공략해봐.'},{name:'질주하는 종이 상자',ids:[2,6,10,14,18],hint:'빠른 연속 공격! 갑옷으로 매번 피해를 줄이거나 가시로 반격해봐.'},{name:'수상한 별빛 마법사',ids:[1,5,8,13,17],hint:'화상이 계속 쌓여! 공격 속도를 높여 빠르게 승부를 내봐.'}];opponent=opponents[(round-1)%opponents.length];puppet($('enemy'),opponent.ids);$('enemyname').textContent=opponent.name;$('hint').textContent=opponent.hint;const s=stats(opponent.ids);$('enemyhealth').textContent=`${s.hp} / ${s.hp}`;$('enemystats').textContent=`공격 ${s.atk} · 방어 ${s.armor} · 초당 ${s.speed.toFixed(2)}회`;$('enemyhp').style.width='100%'}
function render(){puppet($('player'),selected);$('record').textContent=`${wins}승`;$('count').textContent=`${unlocked.size}/20`;$('round').textContent=`ROUND ${String(round).padStart(2,'0')}`;$('slots').innerHTML=names.map((name,i)=>{let p=selected[i]===null?null:parts[selected[i]];return `<article class="slot"><div class="slot-label"><span>${name}</span><span class="pips" aria-label="남은 기회 ${3-rolls[i]}번">${'●'.repeat(3-rolls[i])}${'○'.repeat(rolls[i])}</span></div>${p?`<div class="icon" style="${sprite(p.id)}"></div>`:'<div class="question">?</div>'}<strong>${p?p.name:'빈 페이지'}</strong><p class="desc">${p?p.desc:'어떤 파츠가 나올까?'}</p><button data-roll="${i}" ${mode!=='build'||busy.has(i)||rolls[i]>=3?'disabled':''}>${busy.has(i)?'돌아가는 중…':rolls[i]===3?'기회 소진':p?'다시 돌리기':'룰렛 돌리기'}</button></article>`}).join('');document.querySelectorAll('[data-roll]').forEach(b=>b.onclick=()=>spin(Number(b.dataset.roll)));const s=stats(selected);$('mystats').textContent=`공격 ${s.atk} · 방어 ${s.armor} · 초당 ${s.speed.toFixed(2)}회`;$('myhealth').textContent=`${s.hp} / ${s.hp}`;$('myhp').style.width='100%';let syn=matches(selected).map(r=>`<span class="chip">✦ ${r.name}</span>`);const familyInfo={'기사':'주기적 방어막','마법':'3회마다 주문 추가','기계':'공격 속도 +15%','야생':'회피 +8%'};for(const [f,n]of Object.entries(s.families))if(n>=2)syn.push(`<span class="chip">${f} ${n} · ${familyInfo[f]}</span>`);const clue=recipes.find(r=>r.ids.some(i=>selected.includes(i))&&!r.ids.every(i=>selected.includes(i)));$('synergies').innerHTML=syn.join('')+(clue?`<div>단서: ${clue.desc.split(' · ')[0]}</div>`:syn.length?'':'같은 계열 2개를 모으거나 뜻밖의 짝을 찾아봐.');let missing=selected.filter(i=>i===null).length;$('ready').textContent=missing?`${missing}개 부위를 더 뽑아주세요`:'남은 기회를 써도, 지금 싸워도 좋아요';$('fight').disabled=!!missing||busy.size>0||mode!=='build';$('myname').textContent=missing?'아직은 미완성':matches(selected)[0]?.name||'나만의 낙서'}
async function spin(slot){if(!Number.isInteger(slot)||slot<0||slot>4)throw Error('올바른 부위를 선택해주세요.');if(mode!=='build'||busy.has(slot)||rolls[slot]>=3)throw Error('지금은 돌릴 수 없어요.');busy.add(slot);rolls[slot]++;render();const pool=parts.filter(p=>p.slot===slot&&unlocked.has(p.id));for(let k=0;k<9;k++){selected[slot]=rand(pool).id;const card=$('slots').children[slot];card.querySelector('strong').textContent=parts[selected[slot]].name;card.classList.add('rolling');await new Promise(r=>setTimeout(r,55+k*7))}busy.delete(slot);render();return {slot: names[slot],part:parts[selected[slot]].name,remaining:3-rolls[slot]}}
function log(t){$('battlelog').textContent=t}
function animate(id,cls){const e=$(id);e.classList.remove(cls);void e.offsetWidth;e.classList.add(cls)}
function damage(target,n){let blocked=Math.min(target.barrier,n);target.barrier-=blocked;target.health-=n-blocked}
function hit(a,b,label,el,targetEl){a.attacks++;animate(el,'attack');if(Math.random()<b.evade){log(`${label}의 공격을 회피!`);return}let d=Math.max(2,a.atk-Math.max(0,b.armor-a.pierce))+a.magic;if(a.echo&&a.attacks%3===0)d+=a.magic+6;damage(b,d);if(a.erase)b.armor=Math.max(0,b.armor-1);b.fire+=a.burn;if(a.stun&&a.attacks%3===0){b.stunned=1.3;log('쿵! 내려찍기 — 1.3초 기절')}else log(`${label}의 공격! ${Math.round(d)} 피해`);if(b.thorns)damage(a,b.thorns);animate(targetEl,'hurt')}
function startFight(){if(mode!=='build'||busy.size||selected.includes(null))throw Error('다섯 부위를 먼저 완성해주세요.');mode='battle';render();$('phase').textContent='02. 자동 결투';$('ready').textContent='선택한 조합으로 싸우는 중';$('fight').textContent='결투 중…';const make=ids=>{const s=stats(ids);return {...s,health:s.hp,barrier:s.shield,fire:0,charge:0,attacks:0,stunned:0}};combat=[make(selected),make(opponent.ids)];elapsed=0;clockId=setInterval(tick,100);return {status:'battle_started'}}
function tick(){elapsed+=.1;const [a,b]=combat;for(let i=0;i<2;i++){const x=combat[i],y=combat[1-i];x.stunned=Math.max(0,x.stunned-.1);x.health-=x.fire*.1;if(Math.floor(elapsed*10)%60===0&&x.shield)x.barrier=x.shield;if(x.stunned===0)x.charge+=.1*x.speed*(1-y.slow)}if(a.health>0&&b.health>0){if(a.charge>=1){a.charge--;hit(a,b,'내 낙서','player','enemy')}if(b.health>0&&a.health>0&&b.charge>=1){b.charge--;hit(b,a,'상대','enemy','player')}}for(let i=0;i<2;i++){let x=combat[i],prefix=i?'enemy':'my';$(prefix+'hp').style.width=`${Math.max(0,x.health/x.hp*100)}%`;$(prefix+'health').textContent=`${Math.max(0,Math.ceil(x.health))} / ${x.hp}${x.barrier>0?' + 방어막 '+Math.ceil(x.barrier):''}`}$('timer').textContent=`${elapsed.toFixed(1)}초`;if(a.health<=0||b.health<=0||elapsed>=45){const outcome=a.health<=0&&b.health<=0?'draw':a.health<=0?'lose':b.health<=0?'win':a.health/a.hp===b.health/b.hp?'draw':a.health/a.hp>b.health/b.hp?'win':'lose';finish(outcome)}}
function finish(outcome){clearInterval(clockId);mode='result';$('phase').textContent='03. 결투 결과';let reward='';if(outcome==='win'){wins++;const locked=parts.filter(p=>!unlocked.has(p.id));if(locked.length){const p=rand(locked);unlocked.add(p.id);reward=`새 파츠 해금: ${p.name}! 다음 판 룰렛에 추가됐어요.`}else reward='모든 파츠를 해금했어요! 새로운 조합에 도전해봐.';try{localStorage.setItem('doodle-v1',JSON.stringify({wins,unlocked:[...unlocked]}))}catch{reward+=' 저장 공간을 사용할 수 없어 이번 접속에서만 유지됩니다.'}}$('record').textContent=`${wins}승`;$('count').textContent=`${unlocked.size}/20`;$('result').hidden=false;$('result').innerHTML=`<h2>${outcome==='win'?'승리! 이번 장은 네 거야.':outcome==='draw'?'무승부! 막상막하였어.':'패배… 다음 장에서 다시!'}</h2><p>${reward||'상대의 특성을 보고 다른 조합으로 도전해봐. 해금한 파츠는 유지돼요.'}</p>${elapsed>=45?'<p>45초 종료 · 남은 체력 비율로 판정했어요.</p>':''}<button id="next">${outcome==='win'?'다음 상대 만나기':'다시 조합하기'}</button>`;$('next').onclick=()=>{if(outcome==='win')round++;selected.fill(null);rolls.fill(0);mode='build';$('result').hidden=true;$('battlelog').textContent='';$('phase').textContent='01. 조합하기';$('timer').textContent='연필 준비!';$('fight').textContent='조합 확정 · 결투 시작';chooseEnemy();render()}}
function showBook(){$('collection').innerHTML=parts.map(p=>`<div class="collect ${unlocked.has(p.id)?'':'locked'}"><div class="icon" style="${sprite(p.id)}"></div><strong>${unlocked.has(p.id)?p.name:'🔒 '+p.name}</strong><small>${names[p.slot]} · ${p.family}</small><small>${p.desc}</small></div>`).join('');$('recipes').innerHTML=recipes.map(r=>`<div class="recipe"><b>${r.name}</b><br>${r.desc}</div>`).join('');$('codex').showModal()}
$('fight').onclick=startFight;$('book').onclick=showBook;$('closebook').onclick=()=>$('codex').close();chooseEnemy();render();
if(document.modelContext?.registerTool){for(const tool of [{name:'read_battle_state',description:'현재 파츠, 남은 룰렛 기회와 전투 상태를 읽습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({mode,selected:selected.map(i=>i===null?null:parts[i].name),remaining:rolls.map(n=>3-n),opponent:opponent.name,wins})},{name:'spin_part_roulette',description:'선택한 부위의 기회 1회를 사용해 파츠를 다시 뽑습니다.',inputSchema:{type:'object',properties:{slot:{type:'integer',minimum:0,maximum:4}},required:['slot'],additionalProperties:false},execute:input=>spin(input.slot)},{name:'start_auto_battle',description:'현재 다섯 파츠를 확정하고 자동 결투를 시작합니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:startFight}])try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{})}catch{}}
